# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/page01.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 804)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setStyleSheet("QWidget {\n"
"    color: rgb(206, 253, 255);\n"
"    \n"
"    background-color: rgb(19, 22, 26);\n"
"}\n"
"\n"
"QLabel {\n"
"   \n"
"    background-color: rgb(35, 45, 53);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(48, 52, 65);\n"
"}\n"
"QHeaderView::section {\n"
"    \n"
"    background-color: rgb(60, 64, 77);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_Search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.verticalLayout.addWidget(self.pushButton_Search)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.pushButton_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.verticalLayout.addWidget(self.pushButton_Delete)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "oldフォルダ一覧"))
        self.pushButton_Search.setText(_translate("MainWindow", "Search"))
        self.pushButton_Delete.setText(_translate("MainWindow", "Delete"))
